services:
  - type: web
    name: pr-sage
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: REPO
        sync: false
      - key: MODEL_NAME
        value: llama-3.1-8b-instant
      - key: DRY_RUN
        value: "true"
      - key: PYTHON_VERSION
        value: 3.11.0
